stages:
  - build_push
  - update

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/test_kode
  IMAGE_TAG: dev_${CI_PIPELINE_ID}
  FULL_IMAGE: "${IMAGE_NAME}:${IMAGE_TAG}"
  SERVICE_NAME: dev_frontend

build_and_push:
  stage: build_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - |
      # Değişkenleri temizle
      CLEAN_IMAGE_NAME=$(echo "$IMAGE_NAME" | tr -d '\n\r')
      CLEAN_IMAGE_TAG=$(echo "$IMAGE_TAG" | tr -d '\n\r')
      CLEAN_FULL_IMAGE="${CLEAN_IMAGE_NAME}:${CLEAN_IMAGE_TAG}"
      
      echo "BUILDING IMAGE: ${CLEAN_FULL_IMAGE}"
      docker build -t "${CLEAN_FULL_IMAGE}" .
      echo "BUILD COMPLETED."

      echo "Logging into GitLab Container Registry..."
      echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      echo "PUSHING IMAGE TO REGISTRY: ${CLEAN_FULL_IMAGE}"
      docker push "${CLEAN_FULL_IMAGE}"
      echo "PUSH COMPLETED."
      
      # Temizlenmiş değişkenleri sonraki job için export et
      echo "CLEAN_FULL_IMAGE=${CLEAN_FULL_IMAGE}" > build_vars.env
  artifacts:
    reports:
      dotenv: build_vars.env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

update:
  stage: update
  tags:
    - 60.33_runner
  script:
    - echo "Logging into GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - echo "Updating Docker service..."
    - docker service update --with-registry-auth --image "$FULL_IMAGE" "$SERVICE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build_and_push