stages:
  - build_push
  - update

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/test_kode
  IMAGE_TAG: dev_${CI_PIPELINE_ID}
  FULL_IMAGE: "${IMAGE_NAME}:${IMAGE_TAG}"
  SERVICE_NAME: dev_frontend

build_and_push:
  stage: build_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - |
      echo "BUILDING IMAGE: ${FULL_IMAGE}"
      docker build -t "${FULL_IMAGE}" .
      echo "BUILD COMPLETED."

      echo "Logging into GitLab Container Registry..."
      echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      echo "PUSHING IMAGE TO REGISTRY: ${FULL_IMAGE}"
      docker push "${FULL_IMAGE}"
      echo "PUSH COMPLETED."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

update:
  stage: update
  # shell executor'da image tanımı gereksiz ama zarar da vermez
  script:
    - echo "Logging into GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - echo "Updating Docker service..."
    - docker service update --with-registry-auth --image "$FULL_IMAGE" "$SERVICE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build_and_push
