stages:
  - build_push
  - update

variables:
  SERVICE_NAME: dev_frontend

build_and_push:
  stage: build_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - |
      # Değişkenleri script içinde tanımla ve temizle
      CLEAN_REGISTRY_IMAGE=$(echo "$CI_REGISTRY_IMAGE" | tr -d '\n\r' | sed 's/[[:space:]]*$//')
      IMAGE_NAME="${CLEAN_REGISTRY_IMAGE}/test_kode"
      IMAGE_TAG="dev_${CI_PIPELINE_ID}"
      FULL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
      
      echo "DEBUG: CLEAN_REGISTRY_IMAGE=[${CLEAN_REGISTRY_IMAGE}]"
      echo "DEBUG: IMAGE_NAME=[${IMAGE_NAME}]"
      echo "DEBUG: IMAGE_TAG=[${IMAGE_TAG}]"
      echo "DEBUG: FULL_IMAGE=[${FULL_IMAGE}]"
      
      echo "BUILDING IMAGE: ${FULL_IMAGE}"
      docker build -t "${FULL_IMAGE}" .
      echo "BUILD COMPLETED."

      echo "Logging into GitLab Container Registry..."
      echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      echo "PUSHING IMAGE TO REGISTRY: ${FULL_IMAGE}"
      docker push "${FULL_IMAGE}"
      echo "PUSH COMPLETED."
      
      # Sonraki job için değişkeni export et
      echo "FULL_IMAGE=${FULL_IMAGE}" > build_vars.env
  artifacts:
    reports:
      dotenv: build_vars.env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

update:
  stage: update
  script:
    - |
      # Eğer önceki job'dan gelen değişken yoksa, yeniden oluştur
      if [ -z "$FULL_IMAGE" ]; then
        CLEAN_REGISTRY_IMAGE=$(echo "$CI_REGISTRY_IMAGE" | tr -d '\n\r' | sed 's/[[:space:]]*$//')
        IMAGE_NAME="${CLEAN_REGISTRY_IMAGE}/test_kode"
        IMAGE_TAG="dev_${CI_PIPELINE_ID}"
        FULL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
      fi
      
      echo "Logging into GitLab Container Registry..."
      echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      echo "Updating Docker service with image: ${FULL_IMAGE}"
      docker service update --with-registry-auth --image "${FULL_IMAGE}" "$SERVICE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build_and_push