stages:
  - test_kube_config

test_kube_config:
  stage: test_kube_config
  image: alpine:latest
  script:
    - echo "Testing KUBE_CONFIG variable..."
    - echo "KUBE_CONFIG length:" $(echo "$KUBE_CONFIG" | wc -c)
    - echo "First 100 chars:" $(echo "$KUBE_CONFIG" | head -c 100)
    - echo "Decoding test..."
    - echo "$KUBE_CONFIG" | base64 -d | head -5
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
