stages:
  - build_push
  - update

variables:
  SERVICE_NAME: dev_frontend
  IMAGE_TAG: dev_${CI_PIPELINE_IID}
  FULL_IMAGE: $CI_REGISTRY_IMAGE/test_kode:$IMAGE_TAG

build_and_push:
  stage: build_push
  image: docker:latest
  tags:
    - 60.33_docker_runner
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "BUILDING IMAGE: ${FULL_IMAGE}"
    - docker build -t "${FULL_IMAGE}" .
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push "${FULL_IMAGE}"
    - echo "FULL_IMAGE=${FULL_IMAGE}" >> build_vars.env
    - echo "IMAGE_TAG=${IMAGE_TAG}" >> build_vars.env
  artifacts:
    reports:
      dotenv: build_vars.env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

update:
  stage: update
  tags:
    - 60.33_docker_runner
  before_script:
    - echo "Checking Docker availability..."
    - docker --version
    - docker info
  script:
    - echo "FULL_IMAGE: $FULL_IMAGE"
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker pull "$FULL_IMAGE"
    - docker service update --with-registry-auth --image "$FULL_IMAGE" "$SERVICE_NAME"
    - echo "Service update completed successfully!"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build_and_push