apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }} 