name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST \
            -F token=$GITLAB_TOKEN \
            -F ref=main \
            https://gitlab.com/api/v4/projects/71488582/trigger/pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
