name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/71488582/trigger/pipeline \
            --data-urlencode "token=$GITLAB_TOKEN" \
            --data-urlencode "ref=main"
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
